# Generated by Django 5.0.2 on 2024-04-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabApp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='bkapmtHaemolgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
                ('city', models.TextField()),
            ],
        ),
    ]
